# Generated by Django 6.0 on 2025-12-04 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField()),
                ('cantidad_peces', models.PositiveIntegerField()),
                ('peso_promedio_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_por_pez', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagos.lago')),
            ],
        ),
    ]
