# Generated by Django 6.0 on 2025-12-04 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagos', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_alimento', models.CharField(max_length=100)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_por_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('lago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagos.lago')),
            ],
        ),
    ]
