# Generated by Django 6.0 on 2025-12-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagos', '0001_initial'),
        ('produccion', '0002_alimentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_muestreada', models.PositiveIntegerField(default=30)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peso_promedio', models.DecimalField(decimal_places=3, editable=False, max_digits=6)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagos.lago')),
            ],
        ),
    ]
