# Generated by Django 6.0 on 2025-12-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagos', '0001_initial'),
        ('produccion', '0003_muestreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilos_vendidos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('lago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lagos.lago')),
            ],
        ),
    ]
